### PR TITLE
Immediately set text when set date.

### PR DESCRIPTION
**Pull request by granoeste**
The following code is also possible, however a little bit troublesome...
```
            Calendar calendar = Calendar.getInstance();
            datePickerEditText.onDateSet(
                    null,
                    calendar.get(Calendar.YEAR),
                    calendar.get(Calendar.MONTH),
                    calendar.get(Calendar.DAY_OF_MONTH));
```

### CODE REVIEW

**Comment by JonatanSalas** [comment]
@granoeste so, you want the first date you set programmatically to the DatePicker been set as the default date on the EditText, that's right? If so, it seems good to me!

**Comment by granoeste** [comment]
@JonatanSalas Exactly! I would like it.

**Comment by JonatanSalas** [comment]
@granoeste great! So, let's merge it! Thank you for your contribution! 😄

**Comment by JonatanSalas** [comment]
@granoeste I have released v0.3.3

**Pull request merged**
