### PR TITLE
Project updated to work on latest android versions. 

### PR DESCRIPTION
**Pull request by OmarShoaib**
Project has been updated to latest android version plus the default date format has been updated from dd/MM/yyyy to yyyy-MM-dd.

### CODE REVIEW

**Comment by JonatanSalas** [comment]
Hi @OmarShoaib, first of all thank you for your very first contribution. We're glad to see that there's people interested in helping improve our OSS packages.

I'll start reviewing the code and if there's no issue I'll proceed to merge it.

**Comment by OmarShoaib** [comment]
Thanks alot. It'll be really grateful to you.

**Comment by JonatanSalas** [comment]
@OmarShoaib everything seems fine, so proceeding to merge it. Thank you very much for your contribution. I'll generate a newer release and update the README.md to reflect your changes!

**Review by JonatanSalas — APPROVED** [review]

**Comment by JonatanSalas** [comment]
@OmarShoaib I've released a new tag with version `v0.5.0`. You can install and use it. 

BTW, also I've mention you on the release, thanks! We're glad to see people that's interested in improving our OSS packages.

**Comment by OmarShoaib** [comment]
@JonatanSalas Thank you for your prompt response. Really appreciated!

**Pull request merged**
